# Generated by Django 5.0 on 2023-12-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Riddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("enable", models.BooleanField(default=False)),
            ],
        ),
    ]
